### ISSUE TITLE
Disk cache is not usable after calling diskCache.clearCache();

### ISSUE THREAD

**Issue by romanlum** [iainconnor/ObjectCache#2]
If you call diskCache.clearCache() as you sugget on the Readme, the cache is not usable after this call.

It throws an exception

```
W/System.err(  903): java.lang.IllegalStateException: cache is closed
W/System.err(  903):    at com.jakewharton.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:614)
W/System.err(  903):    at com.jakewharton.disklrucache.DiskLruCache.edit(DiskLruCache.java:454)
W/System.err(  903):    at com.jakewharton.disklrucache.DiskLruCache.edit(DiskLruCache.java:450)
W/System.err(  903):    at com.iainconnor.objectcache.DiskCache.setKeyValue(DiskCache.java:62)
W/System.err(  903):    at com.iainconnor.objectcache.CacheManager.put(CacheManager.java:110)
W/System.err(  903):    at at.lumetsnet.fuelmanager.app.services.DiskCacheService.put(DiskCacheService.java:74)
W/System.err(  903):    at at.lumetsnet.fuelmanager.app.services.FuelManagerApiService.getVehicle(FuelManagerApiService.java:128)
W/System.err(  903):    at at.lumetsnet.fuelmanager.app.viewmodels.ShowVehicleViewModel$1.doInBackground(ShowVehicleViewModel.java:59)
W/System.err(  903):    at at.lumetsnet.fuelmanager.app.viewmodels.ShowVehicleViewModel$1.doInBackground(ShowVehicleViewModel.java:56)
W/System.err(  903):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(  903):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(  903):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(  903):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(  903):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(  903):    at java.lang.Thread.run(Thread.java:841)
```

I made a pull request as fix
see https://github.com/iainconnor/ObjectCache/pull/1

**Comment by antonshkurenko** [comment]
Thanks, also.
